/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Current user + role. Used by the frontend route guard (Next.js proxy) and to bootstrap
         *     the `csrftoken` cookie. Always 200: `user` is null for anonymous visitors.
         */
        get: operations["auth_session_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness/readiness probe for Docker healthchecks. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/consent-documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Currently valid consent texts the participant can grant. */
        get: operations["participant_consent_documents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/consent-documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Currently valid consent texts the participant can grant. */
        get: operations["participant_consent_documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/consents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The participant's full consent history. No update/delete: withdraw via the action. */
        get: operations["participant_consents_list"];
        put?: never;
        /** @description The participant's full consent history. No update/delete: withdraw via the action. */
        post: operations["participant_consents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/consents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The participant's full consent history. No update/delete: withdraw via the action. */
        get: operations["participant_consents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/consents/{id}/withdraw/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description The participant's full consent history. No update/delete: withdraw via the action. */
        post: operations["participant_consents_withdraw_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/enrollments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["participant_enrollments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/enrollments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["participant_enrollments_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/enrollments/{id}/withdraw/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["participant_enrollments_withdraw_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/my-data/access-log/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Who did what with the participant's data (based on django-auditlog). */
        get: operations["participant_my_data_access_log_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/my-data/deletion-requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request erasure of the account and data (GDPR art. 17). */
        get: operations["participant_my_data_deletion_requests_list"];
        put?: never;
        /** @description Request erasure of the account and data (GDPR art. 17). */
        post: operations["participant_my_data_deletion_requests_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/my-data/deletion-requests/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request erasure of the account and data (GDPR art. 17). */
        get: operations["participant_my_data_deletion_requests_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/my-data/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Download all personal data as JSON (GDPR art. 15 & 20). */
        get: operations["participant_my_data_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/notification-preferences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["participant_notification_preferences_retrieve"];
        put: operations["participant_notification_preferences_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["participant_notification_preferences_partial_update"];
        trace?: never;
    };
    "/participant/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["participant_profile_retrieve"];
        put: operations["participant_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["participant_profile_partial_update"];
        trace?: never;
    };
    "/participant/questionnaires/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Questionnaires of studies the participant is enrolled in. */
        get: operations["participant_questionnaires_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/questionnaires/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Questionnaires of studies the participant is enrolled in. */
        get: operations["participant_questionnaires_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/questionnaires/{id}/response/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET the participant's draft/submitted answers; PUT to save a draft or submit (`submit: true`). */
        get: operations["participant_questionnaires_response_retrieve"];
        /** @description GET the participant's draft/submitted answers; PUT to save a draft or submit (`submit: true`). */
        put: operations["participant_questionnaires_response_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/studies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search published studies, get recommendations and apply. */
        get: operations["participant_studies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/studies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search published studies, get recommendations and apply. */
        get: operations["participant_studies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/studies/{id}/apply/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Search published studies, get recommendations and apply. */
        post: operations["participant_studies_apply_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/participant/studies/recommended/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search published studies, get recommendations and apply. */
        get: operations["participant_studies_recommended_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/researcher/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["researcher_profile_retrieve"];
        put: operations["researcher_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["researcher_profile_partial_update"];
        trace?: never;
    };
    "/researcher/studies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Studies the researcher has object permissions for (django-guardian). */
        get: operations["researcher_studies_list"];
        put?: never;
        /** @description Studies the researcher has object permissions for (django-guardian). */
        post: operations["researcher_studies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/researcher/studies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Studies the researcher has object permissions for (django-guardian). */
        get: operations["researcher_studies_retrieve"];
        /** @description Studies the researcher has object permissions for (django-guardian). */
        put: operations["researcher_studies_update"];
        post?: never;
        /** @description Studies the researcher has object permissions for (django-guardian). */
        delete: operations["researcher_studies_destroy"];
        options?: never;
        head?: never;
        /** @description Studies the researcher has object permissions for (django-guardian). */
        patch: operations["researcher_studies_partial_update"];
        trace?: never;
    };
    "/researcher/studies/{id}/close/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Studies the researcher has object permissions for (django-guardian). */
        post: operations["researcher_studies_close_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/researcher/studies/{id}/criteria/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Studies the researcher has object permissions for (django-guardian). */
        get: operations["researcher_studies_criteria_retrieve"];
        /** @description Studies the researcher has object permissions for (django-guardian). */
        put: operations["researcher_studies_criteria_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/researcher/studies/{id}/publish/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Studies the researcher has object permissions for (django-guardian). */
        post: operations["researcher_studies_publish_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/researcher/studies/{study_pk}/participants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pseudonymised participants of a study. Researchers can only change the enrollment status. */
        get: operations["researcher_studies_participants_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/researcher/studies/{study_pk}/participants/{pseudonym}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pseudonymised participants of a study. Researchers can only change the enrollment status. */
        get: operations["researcher_studies_participants_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Pseudonymised participants of a study. Researchers can only change the enrollment status. */
        patch: operations["researcher_studies_participants_partial_update"];
        trace?: never;
    };
    "/researcher/studies/{study_pk}/questionnaires/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description For views nested under /researcher/studies/<study_pk>/: resolves the study + checks perms. */
        get: operations["researcher_studies_questionnaires_list"];
        put?: never;
        /** @description For views nested under /researcher/studies/<study_pk>/: resolves the study + checks perms. */
        post: operations["researcher_studies_questionnaires_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/researcher/studies/{study_pk}/questionnaires/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description For views nested under /researcher/studies/<study_pk>/: resolves the study + checks perms. */
        get: operations["researcher_studies_questionnaires_retrieve"];
        /** @description For views nested under /researcher/studies/<study_pk>/: resolves the study + checks perms. */
        put: operations["researcher_studies_questionnaires_update"];
        post?: never;
        /** @description For views nested under /researcher/studies/<study_pk>/: resolves the study + checks perms. */
        delete: operations["researcher_studies_questionnaires_destroy"];
        options?: never;
        head?: never;
        /** @description For views nested under /researcher/studies/<study_pk>/: resolves the study + checks perms. */
        patch: operations["researcher_studies_questionnaires_partial_update"];
        trace?: never;
    };
    "/researcher/studies/{study_pk}/questionnaires/{id}/responses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Submitted answers, pseudonymised. Every access is written to the audit log. */
        get: operations["researcher_studies_questionnaires_responses_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Published studies, visible to everyone. */
        get: operations["studies_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/studies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Published studies, visible to everyone. */
        get: operations["studies_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description What happened to the participant's data, and by whom (role only — no staff identities). */
        AccessLogEntry: {
            readonly id: number;
            /** Format: date-time */
            readonly timestamp: string;
            readonly action: string;
            readonly object_type: string;
            readonly actor: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Consent: {
            /** Format: uuid */
            readonly id: string;
            readonly document: components["schemas"]["ConsentDocument"];
            /** Format: date-time */
            readonly granted_at: string;
            /** Format: date-time */
            readonly withdrawn_at: string | null;
            readonly is_active: boolean;
        };
        ConsentDocument: {
            /** Format: uuid */
            readonly id: string;
            readonly kind: components["schemas"]["KindEnum"];
            readonly version: string;
            /** @default sk */
            readonly language: components["schemas"]["LanguageEnum"];
            readonly title: string;
            readonly text: string;
            /** Format: date-time */
            readonly published_at: string | null;
        };
        ConsentRequest: {
            /** Format: uuid */
            document_id: string;
        };
        DeletionRequest: {
            /** Format: uuid */
            readonly id: string;
            readonly status: components["schemas"]["DeletionRequestStatusEnum"];
            reason?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly processed_at: string | null;
        };
        DeletionRequestRequest: {
            reason?: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `processing` - Processing
         *     * `completed` - Completed
         *     * `rejected` - Rejected
         * @enum {string}
         */
        DeletionRequestStatusEnum: "pending" | "processing" | "completed" | "rejected";
        EligibilityCriteria: {
            min_age?: number | null;
            max_age?: number | null;
            sex?: components["schemas"]["EligibilityCriteriaSexEnum"];
            regions?: components["schemas"]["RegionEnum"][];
            diagnoses?: string[];
        };
        EligibilityCriteriaRequest: {
            min_age?: number | null;
            max_age?: number | null;
            sex?: components["schemas"]["EligibilityCriteriaSexEnum"];
            regions?: components["schemas"]["RegionEnum"][];
            diagnoses?: string[];
        };
        /**
         * @description * `any` - Any
         *     * `female` - Female
         *     * `male` - Male
         * @enum {string}
         */
        EligibilityCriteriaSexEnum: "any" | "female" | "male";
        /** @description Participant's own view of an enrollment. */
        Enrollment: {
            /** Format: uuid */
            readonly id: string;
            readonly study: components["schemas"]["PublicStudy"];
            readonly status: components["schemas"]["EnrollmentStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `applied` - Applied
         *     * `enrolled` - Enrolled
         *     * `withdrawn` - Withdrawn
         *     * `completed` - Completed
         * @enum {string}
         */
        EnrollmentStatusEnum: "applied" | "enrolled" | "withdrawn" | "completed";
        Health: {
            status: string;
        };
        /**
         * @description * `health_data_processing` - Processing of health data
         *     * `study_matching_contact` - Contact about matching studies
         *     * `terms` - Terms of use
         * @enum {string}
         */
        KindEnum: "health_data_processing" | "study_matching_contact" | "terms";
        /**
         * @description * `sk` - Slovenčina
         *     * `en` - English
         * @enum {string}
         */
        LanguageEnum: "sk" | "en";
        NotificationPreference: {
            email_matching_studies?: boolean;
            email_study_updates?: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
        NotificationPreferenceRequest: {
            email_matching_studies?: boolean;
            email_study_updates?: boolean;
        };
        Organization: {
            /** Format: uuid */
            readonly id: string;
            readonly name: string;
            readonly is_verified: boolean;
        };
        PaginatedAccessLogEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AccessLogEntry"][];
        };
        PaginatedConsentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Consent"][];
        };
        PaginatedDeletionRequestList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DeletionRequest"][];
        };
        PaginatedEnrollmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Enrollment"][];
        };
        PaginatedPseudonymizedEnrollmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PseudonymizedEnrollment"][];
        };
        PaginatedPseudonymizedResponseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PseudonymizedResponse"][];
        };
        PaginatedPublicStudyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PublicStudy"][];
        };
        PaginatedQuestionnaireList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Questionnaire"][];
        };
        PaginatedResearcherStudyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ResearcherStudy"][];
        };
        ParticipantProfile: {
            birth_year?: number | null;
            sex?: components["schemas"]["ParticipantProfileSexEnum"] | components["schemas"]["BlankEnum"];
            region?: components["schemas"]["RegionEnum"] | components["schemas"]["BlankEnum"];
            diagnoses?: string[];
            /** Format: date-time */
            readonly updated_at: string;
        };
        ParticipantProfileRequest: {
            birth_year?: number | null;
            sex?: components["schemas"]["ParticipantProfileSexEnum"] | components["schemas"]["BlankEnum"];
            region?: components["schemas"]["RegionEnum"] | components["schemas"]["BlankEnum"];
            diagnoses?: string[];
        };
        /**
         * @description * `female` - Female
         *     * `male` - Male
         *     * `other` - Other
         * @enum {string}
         */
        ParticipantProfileSexEnum: "female" | "male" | "other";
        ParticipantResponse: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly questionnaire: string;
            data?: unknown;
            /** Format: date-time */
            readonly submitted_at: string | null;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ParticipantResponseRequest: {
            data?: unknown;
            /** @default false */
            submit: boolean;
        };
        PatchedNotificationPreferenceRequest: {
            email_matching_studies?: boolean;
            email_study_updates?: boolean;
        };
        PatchedParticipantProfileRequest: {
            birth_year?: number | null;
            sex?: components["schemas"]["ParticipantProfileSexEnum"] | components["schemas"]["BlankEnum"];
            region?: components["schemas"]["RegionEnum"] | components["schemas"]["BlankEnum"];
            diagnoses?: string[];
        };
        /** @description Researcher's view: only the per-study pseudonym, never name or email. */
        PatchedPseudonymizedEnrollmentRequest: {
            status?: components["schemas"]["EnrollmentStatusEnum"];
        };
        PatchedQuestionnaireRequest: {
            title?: string;
            schema?: unknown;
            is_active?: boolean;
        };
        PatchedResearcherProfileRequest: {
            institution?: string;
        };
        PatchedResearcherStudyRequest: {
            title?: string;
            description?: string;
            results_summary?: string;
        };
        /** @description Researcher's view: only the per-study pseudonym, never name or email. */
        PseudonymizedEnrollment: {
            /** Format: uuid */
            readonly participant_id: string;
            status: components["schemas"]["EnrollmentStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Researcher view: answers keyed by the per-study pseudonym, never the participant's identity. */
        PseudonymizedResponse: {
            /** Format: uuid */
            readonly id: string;
            readonly participant_id: string | null;
            readonly data: unknown;
            /** Format: date-time */
            readonly submitted_at: string | null;
        };
        PublicStudy: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly description: string;
            readonly status: components["schemas"]["StudyStatusEnum"];
            readonly organization: string;
            /** Format: date-time */
            readonly published_at: string | null;
            readonly results_summary: string;
            readonly criteria: components["schemas"]["EligibilityCriteria"];
        };
        Questionnaire: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly study: string;
            title: string;
            schema?: unknown;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        QuestionnaireRequest: {
            title: string;
            schema?: unknown;
            is_active?: boolean;
        };
        /**
         * @description * `BA` - Bratislavský
         *     * `TT` - Trnavský
         *     * `TN` - Trenčiansky
         *     * `NR` - Nitriansky
         *     * `ZA` - Žilinský
         *     * `BB` - Banskobystrický
         *     * `PO` - Prešovský
         *     * `KE` - Košický
         * @enum {string}
         */
        RegionEnum: "BA" | "TT" | "TN" | "NR" | "ZA" | "BB" | "PO" | "KE";
        ResearcherProfile: {
            institution?: string;
            readonly organization: components["schemas"]["Organization"];
            readonly is_verified: boolean;
        };
        ResearcherProfileRequest: {
            institution?: string;
        };
        ResearcherStudy: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            description: string;
            readonly status: components["schemas"]["StudyStatusEnum"];
            /** Format: uuid */
            readonly organization: string | null;
            results_summary?: string;
            /** Format: date-time */
            readonly published_at: string | null;
            readonly criteria: components["schemas"]["EligibilityCriteria"];
            readonly enrollment_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ResearcherStudyRequest: {
            title: string;
            description: string;
            results_summary?: string;
        };
        /**
         * @description * `participant` - Participant
         *     * `researcher` - Researcher
         *     * `organization` - Organization
         *     * `admin` - Administrator
         * @enum {string}
         */
        RoleEnum: "participant" | "researcher" | "organization" | "admin";
        Session: {
            is_authenticated: boolean;
            user: components["schemas"]["SessionUser"] | null;
        };
        SessionUser: {
            /** Format: uuid */
            readonly id: string;
            /**
             * E-mailová adresa
             * Format: email
             */
            email: string;
            role?: components["schemas"]["RoleEnum"];
            /** Krstné meno */
            first_name?: string;
            /** Priezvisko */
            last_name?: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `published` - Published
         *     * `closed` - Closed
         * @enum {string}
         */
        StudyStatusEnum: "draft" | "published" | "closed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_session_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    participant_consent_documents_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentDocument"][];
                };
            };
        };
    };
    participant_consent_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentDocument"];
                };
            };
        };
    };
    participant_consents_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConsentList"];
                };
            };
        };
    };
    participant_consents_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ConsentRequest"];
                "multipart/form-data": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
        };
    };
    participant_consents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
        };
    };
    participant_consents_withdraw_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
        };
    };
    participant_enrollments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEnrollmentList"];
                };
            };
        };
    };
    participant_enrollments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
        };
    };
    participant_enrollments_withdraw_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
        };
    };
    participant_my_data_access_log_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccessLogEntryList"];
                };
            };
        };
    };
    participant_my_data_deletion_requests_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDeletionRequestList"];
                };
            };
        };
    };
    participant_my_data_deletion_requests_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeletionRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DeletionRequestRequest"];
                "multipart/form-data": components["schemas"]["DeletionRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionRequest"];
                };
            };
        };
    };
    participant_my_data_deletion_requests_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletionRequest"];
                };
            };
        };
    };
    participant_my_data_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    participant_notification_preferences_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
        };
    };
    participant_notification_preferences_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NotificationPreferenceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NotificationPreferenceRequest"];
                "multipart/form-data": components["schemas"]["NotificationPreferenceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
        };
    };
    participant_notification_preferences_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNotificationPreferenceRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNotificationPreferenceRequest"];
                "multipart/form-data": components["schemas"]["PatchedNotificationPreferenceRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
        };
    };
    participant_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    participant_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ParticipantProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ParticipantProfileRequest"];
                "multipart/form-data": components["schemas"]["ParticipantProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    participant_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedParticipantProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedParticipantProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedParticipantProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantProfile"];
                };
            };
        };
    };
    participant_questionnaires_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedQuestionnaireList"];
                };
            };
        };
    };
    participant_questionnaires_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Questionnaire"];
                };
            };
        };
    };
    participant_questionnaires_response_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantResponse"];
                };
            };
        };
    };
    participant_questionnaires_response_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ParticipantResponseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ParticipantResponseRequest"];
                "multipart/form-data": components["schemas"]["ParticipantResponseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantResponse"];
                };
            };
        };
    };
    participant_studies_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicStudyList"];
                };
            };
        };
    };
    participant_studies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStudy"];
                };
            };
        };
    };
    participant_studies_apply_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
        };
    };
    participant_studies_recommended_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicStudyList"];
                };
            };
        };
    };
    researcher_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherProfile"];
                };
            };
        };
    };
    researcher_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ResearcherProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ResearcherProfileRequest"];
                "multipart/form-data": components["schemas"]["ResearcherProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherProfile"];
                };
            };
        };
    };
    researcher_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedResearcherProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedResearcherProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedResearcherProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherProfile"];
                };
            };
        };
    };
    researcher_studies_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResearcherStudyList"];
                };
            };
        };
    };
    researcher_studies_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearcherStudyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ResearcherStudyRequest"];
                "multipart/form-data": components["schemas"]["ResearcherStudyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherStudy"];
                };
            };
        };
    };
    researcher_studies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherStudy"];
                };
            };
        };
    };
    researcher_studies_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearcherStudyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ResearcherStudyRequest"];
                "multipart/form-data": components["schemas"]["ResearcherStudyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherStudy"];
                };
            };
        };
    };
    researcher_studies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    researcher_studies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedResearcherStudyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedResearcherStudyRequest"];
                "multipart/form-data": components["schemas"]["PatchedResearcherStudyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherStudy"];
                };
            };
        };
    };
    researcher_studies_close_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherStudy"];
                };
            };
        };
    };
    researcher_studies_criteria_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityCriteria"];
                };
            };
        };
    };
    researcher_studies_criteria_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EligibilityCriteriaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EligibilityCriteriaRequest"];
                "multipart/form-data": components["schemas"]["EligibilityCriteriaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityCriteria"];
                };
            };
        };
    };
    researcher_studies_publish_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearcherStudy"];
                };
            };
        };
    };
    researcher_studies_participants_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPseudonymizedEnrollmentList"];
                };
            };
        };
    };
    researcher_studies_participants_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pseudonym: string;
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PseudonymizedEnrollment"];
                };
            };
        };
    };
    researcher_studies_participants_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pseudonym: string;
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPseudonymizedEnrollmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPseudonymizedEnrollmentRequest"];
                "multipart/form-data": components["schemas"]["PatchedPseudonymizedEnrollmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PseudonymizedEnrollment"];
                };
            };
        };
    };
    researcher_studies_questionnaires_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedQuestionnaireList"];
                };
            };
        };
    };
    researcher_studies_questionnaires_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionnaireRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["QuestionnaireRequest"];
                "multipart/form-data": components["schemas"]["QuestionnaireRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Questionnaire"];
                };
            };
        };
    };
    researcher_studies_questionnaires_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Questionnaire"];
                };
            };
        };
    };
    researcher_studies_questionnaires_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionnaireRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["QuestionnaireRequest"];
                "multipart/form-data": components["schemas"]["QuestionnaireRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Questionnaire"];
                };
            };
        };
    };
    researcher_studies_questionnaires_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    researcher_studies_questionnaires_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedQuestionnaireRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedQuestionnaireRequest"];
                "multipart/form-data": components["schemas"]["PatchedQuestionnaireRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Questionnaire"];
                };
            };
        };
    };
    researcher_studies_questionnaires_responses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                id: string;
                study_pk: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPseudonymizedResponseList"];
                };
            };
        };
    };
    studies_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicStudyList"];
                };
            };
        };
    };
    studies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStudy"];
                };
            };
        };
    };
}
